FROM node as react-build
RUN npm config set registry http://registry.npmjs.org/
WORKDIR /app
COPY package.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx
WORKDIR /usr/share/nginx/html
COPY --from=react-build /app/build .